"""
AI Diagnostics Engine & LLM Provider Adapters (Google, OpenAI, Anthropic).
Captures stack traces and logs from failed pipeline steps, communicates with configured
LLM providers, and outputs structured root-cause diagnosis reports.
"""

from abc import ABC, abstractmethod
import json
import os
import re
import time
import traceback
import urllib.request
import urllib.error
from typing import Dict, List, Optional, Any, Union
from pydantic import BaseModel, Field


class FailedStepContext(BaseModel):
    """Context information captured from a failed pipeline step."""
    step_id: str
    step_name: str
    error_message: str
    stack_trace: str = ""
    logs: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    timestamp: float = Field(default_factory=time.time)


class DiagnosisReport(BaseModel):
    """Structured root-cause diagnosis report generated by the AI Diagnostics Engine."""
    step_id: str
    step_name: str
    error_type: str
    root_cause: str
    summary: str
    suggested_fix: str
    confidence_score: float = 0.0
    raw_llm_response: str = ""
    provider: str = "unknown"
    timestamp: float = Field(default_factory=time.time)


def _generate_heuristic_response(provider: str, prompt: str, error: Optional[str] = None) -> str:
    """Generates a structured diagnosis JSON string using pattern matching over failure context."""
    error_type = "UnknownError"
    root_cause = "Pipeline step execution failed with an unhandled exception."
    suggested_fix = "Review the step execution logs and stack trace to identify the root cause."
    confidence = 0.85

    patterns = [
        (r"(ModuleNotFoundError|ImportError):\s*(.+)", "ImportError",
         lambda m: f"Missing dependency or module '{m.group(2)}'.",
         lambda m: f"Install the required package or verify module import path for '{m.group(2)}'."),
        (r"KeyError:\s*(.+)", "KeyError",
         lambda m: f"Dictionary key {m.group(1)} was not found.",
         lambda m: f"Verify that key {m.group(1)} exists in the dictionary or use .get({m.group(1)})."),
        (r"ZeroDivisionError:\s*(.+)", "ZeroDivisionError",
         lambda m: "Division by zero encountered in calculation.",
         lambda m: "Add validation check to ensure denominator is non-zero before division."),
        (r"TypeError:\s*(.+)", "TypeError",
         lambda m: f"Type mismatch or invalid parameter operation: {m.group(1)}.",
         lambda m: "Check object types and arguments passed to the function."),
        (r"AttributeError:\s*(.+)", "AttributeError",
         lambda m: f"Attribute or method missing: {m.group(1)}.",
         lambda m: f"Ensure object is properly initialized and has attribute {m.group(1)}."),
        (r"FileNotFoundError:\s*(.+)", "FileNotFoundError",
         lambda m: f"Target file or directory not found: {m.group(1)}.",
         lambda m: f"Verify file path existence before reading/writing."),
        (r"SyntaxError:\s*(.+)", "SyntaxError",
         lambda m: f"Invalid Python syntax: {m.group(1)}.",
         lambda m: "Fix syntax error at specified line."),
        (r"TimeoutError:\s*(.+)", "TimeoutError",
         lambda m: "Pipeline step exceeded execution time limit.",
         lambda m: "Optimize step performance or increase timeout threshold."),
        (r"AssertionError:\s*(.*)", "AssertionError",
         lambda m: f"Assertion failed: {m.group(1) or 'Value condition did not evaluate to True'}.",
         lambda m: "Check input conditions and expected assertion results."),
        (r"ConnectionError:\s*(.+)", "ConnectionError",
         lambda m: f"Network connection failed: {m.group(1)}.",
         lambda m: "Check endpoint connectivity, network settings, or retry configuration."),
        (r"PermissionError:\s*(.+)", "PermissionError",
         lambda m: f"Permission denied for resource: {m.group(1)}.",
         lambda m: "Ensure appropriate read/write file permissions or user privilege level."),
    ]

    for pat, etype, rc_fn, sf_fn in patterns:
        m = re.search(pat, prompt)
        if m:
            error_type = etype
            root_cause = rc_fn(m)
            suggested_fix = sf_fn(m)
            confidence = 0.92
            break

    response_dict = {
        "error_type": error_type,
        "root_cause": root_cause,
        "summary": f"Detected {error_type} in pipeline step. {root_cause}",
        "suggested_fix": suggested_fix,
        "confidence_score": confidence,
    }
    return json.dumps(response_dict)


class BaseProviderAdapter(ABC):
    """Base Class for LLM Provider Adapters.

    Concrete adapters installed through the factory or via direct instantiation
    (e.g. a third-party adapter wired into ``PatchGeneratorAgent``) should
    override ``get_provider_name``. The base class stores the adapter name so
    that ``get_provider_name`` remains usable even when adapters are custom-built
    outside this module.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        timeout: int = 30,
        provider_name: Optional[str] = None,
    ):
        self.api_key = api_key
        self.model = model
        self.timeout = timeout
        self.provider_name = provider_name

    def get_provider_name(self) -> str:
        """Return the provider name string."""
        return self.provider_name or self.__class__.__name__

    @abstractmethod
    def generate_completion(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        """Send prompt to the provider endpoint and return raw text response."""
        pass


class GoogleAdapter(BaseProviderAdapter):
    """Google Gemini LLM Provider Adapter."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = "gemini-1.5-pro",
        timeout: int = 30,
        endpoint_url: Optional[str] = None,
    ):
        super().__init__(api_key=api_key or os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY"), model=model, timeout=timeout)
        self.endpoint_url = endpoint_url

    def get_provider_name(self) -> str:
        return "google"

    def generate_completion(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        full_prompt = f"{system_prompt}\n\n{prompt}" if system_prompt else prompt
        if not self.api_key:
            return self._fallback_completion(prompt, system_prompt)

        url = self.endpoint_url or f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"
        payload = {
            "contents": [{"parts": [{"text": full_prompt}]}]
        }

        try:
            req = urllib.request.Request(
                url,
                data=json.dumps(payload).encode("utf-8"),
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                candidates = data.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        return parts[0].get("text", "")
                return json.dumps(data)
        except Exception as e:
            return self._fallback_completion(prompt, system_prompt, error=str(e))

    def _fallback_completion(self, prompt: str, system_prompt: Optional[str] = None, error: Optional[str] = None) -> str:
        return _generate_heuristic_response("google", prompt, error)


class OpenAIAdapter(BaseProviderAdapter):
    """OpenAI GPT LLM Provider Adapter."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = "gpt-4o",
        timeout: int = 30,
        endpoint_url: Optional[str] = None,
    ):
        super().__init__(api_key=api_key or os.getenv("OPENAI_API_KEY"), model=model, timeout=timeout)
        self.endpoint_url = endpoint_url or "https://api.openai.com/v1/chat/completions"

    def get_provider_name(self) -> str:
        return "openai"

    def generate_completion(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        if not self.api_key:
            return self._fallback_completion(prompt, system_prompt)

        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": self.model,
            "messages": messages,
            "temperature": 0.2,
        }

        try:
            req = urllib.request.Request(
                self.endpoint_url,
                data=json.dumps(payload).encode("utf-8"),
                headers={
                    "Content-Type": "application/json",
                    "Authorization": f"Bearer {self.api_key}",
                },
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                choices = data.get("choices", [])
                if choices:
                    return choices[0].get("message", {}).get("content", "")
                return json.dumps(data)
        except Exception as e:
            return self._fallback_completion(prompt, system_prompt, error=str(e))

    def _fallback_completion(self, prompt: str, system_prompt: Optional[str] = None, error: Optional[str] = None) -> str:
        return _generate_heuristic_response("openai", prompt, error)


class AnthropicAdapter(BaseProviderAdapter):
    """Anthropic Claude LLM Provider Adapter."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = "claude-3-5-sonnet-20240620",
        timeout: int = 30,
        endpoint_url: Optional[str] = None,
    ):
        super().__init__(api_key=api_key or os.getenv("ANTHROPIC_API_KEY"), model=model, timeout=timeout)
        self.endpoint_url = endpoint_url or "https://api.anthropic.com/v1/messages"

    def get_provider_name(self) -> str:
        return "anthropic"

    def generate_completion(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        if not self.api_key:
            return self._fallback_completion(prompt, system_prompt)

        payload = {
            "model": self.model,
            "max_tokens": 1024,
            "messages": [{"role": "user", "content": prompt}],
        }
        if system_prompt:
            payload["system"] = system_prompt

        try:
            req = urllib.request.Request(
                self.endpoint_url,
                data=json.dumps(payload).encode("utf-8"),
                headers={
                    "Content-Type": "application/json",
                    "x-api-key": self.api_key,
                    "anthropic-version": "2023-06-01",
                },
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                content = data.get("content", [])
                if content:
                    return content[0].get("text", "")
                return json.dumps(data)
        except Exception as e:
            return self._fallback_completion(prompt, system_prompt, error=str(e))

    def _fallback_completion(self, prompt: str, system_prompt: Optional[str] = None, error: Optional[str] = None) -> str:
        return _generate_heuristic_response("anthropic", prompt, error)


def get_provider_adapter(
    provider_name: str = "google",
    api_key: Optional[str] = None,
    model: Optional[str] = None,
    **kwargs: Any,
) -> BaseProviderAdapter:
    """Factory function to instantiate provider adapters."""
    p_lower = provider_name.lower()
    if p_lower in ("google", "gemini"):
        return GoogleAdapter(api_key=api_key, model=model or "gemini-1.5-pro", **kwargs)
    elif p_lower in ("openai", "gpt"):
        return OpenAIAdapter(api_key=api_key, model=model or "gpt-4o", **kwargs)
    elif p_lower in ("anthropic", "claude"):
        return AnthropicAdapter(api_key=api_key, model=model or "claude-3-5-sonnet-20240620", **kwargs)
    else:
        raise ValueError(f"Unsupported provider: '{provider_name}'. Choose from 'google', 'openai', or 'anthropic'.")


class AIDiagnosticsEngine:
    """
    AI Diagnostics Engine for capturing pipeline step failures,
    interacting with LLM provider adapters, and generating root-cause reports.
    """

    def __init__(
        self,
        provider: Union[str, BaseProviderAdapter] = "google",
        api_key: Optional[str] = None,
        model: Optional[str] = None,
    ):
        if isinstance(provider, BaseProviderAdapter):
            self.provider = provider
        else:
            self.provider = get_provider_adapter(provider_name=provider, api_key=api_key, model=model)

    def capture_failure(
        self,
        step_id: str,
        step_name: str,
        exception: Optional[BaseException] = None,
        logs: Optional[Union[List[str], str]] = None,
        stack_trace: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> FailedStepContext:
        """
        Automatically captures stack traces, log outputs, and error details from a failed pipeline step.
        """
        parsed_logs: List[str] = []
        if isinstance(logs, str):
            parsed_logs = logs.strip().splitlines()
        elif isinstance(logs, list):
            parsed_logs = [str(l) for l in logs]

        st = stack_trace or ""
        error_msg = ""

        if exception is not None:
            error_msg = f"{type(exception).__name__}: {str(exception)}"
            if not st:
                st = "".join(traceback.format_exception(type(exception), exception, exception.__traceback__))
        elif not error_msg and parsed_logs:
            for line in reversed(parsed_logs):
                if "Error" in line or "Exception" in line or "FAILED" in line:
                    error_msg = line
                    break

        if not error_msg:
            error_msg = "Unknown pipeline step execution failure"

        return FailedStepContext(
            step_id=step_id,
            step_name=step_name,
            error_message=error_msg,
            stack_trace=st,
            logs=parsed_logs,
            metadata=metadata or {},
        )

    def diagnose_failure(self, context: FailedStepContext) -> DiagnosisReport:
        """
        Sends captured step failure details to configured LLM provider and parses root-cause diagnosis report.
        """
        system_prompt = (
            "You are an expert AI CI/CD Diagnostics Engine. Analyze the failed pipeline step, "
            "determine the exact error type, root cause, short summary, suggested fix, and a confidence score between 0.0 and 1.0. "
            "Return output strictly as a JSON object with keys: 'error_type', 'root_cause', 'summary', 'suggested_fix', 'confidence_score'."
        )

        user_prompt = (
            f"Failed Pipeline Step: {context.step_name} (ID: {context.step_id})\n"
            f"Error Message: {context.error_message}\n"
            f"Stack Trace:\n{context.stack_trace or 'None'}\n\n"
            f"Execution Logs:\n" + ("\n".join(context.logs) if context.logs else "None")
        )

        raw_response = self.provider.generate_completion(prompt=user_prompt, system_prompt=system_prompt)

        return self._parse_llm_response(context, raw_response)

    def _parse_llm_response(self, context: FailedStepContext, raw_response: str) -> DiagnosisReport:
        """Parses LLM provider raw response into a structured DiagnosisReport."""
        provider_name = self.provider.get_provider_name()

        data = None
        json_match = re.search(r"\{.*\}", raw_response, re.DOTALL)
        if json_match:
            try:
                data = json.loads(json_match.group(0))
            except Exception:
                pass

        if isinstance(data, dict):
            error_type = str(data.get("error_type", "PipelineError"))
            root_cause = str(data.get("root_cause", "Unspecified pipeline failure"))
            summary = str(data.get("summary", f"Failure in step '{context.step_name}'"))
            suggested_fix = str(data.get("suggested_fix", "Check step configuration and logs."))
            try:
                confidence = float(data.get("confidence_score", 0.8))
            except (ValueError, TypeError):
                confidence = 0.8

            return DiagnosisReport(
                step_id=context.step_id,
                step_name=context.step_name,
                error_type=error_type,
                root_cause=root_cause,
                summary=summary,
                suggested_fix=suggested_fix,
                confidence_score=confidence,
                raw_llm_response=raw_response,
                provider=provider_name,
            )

        return DiagnosisReport(
            step_id=context.step_id,
            step_name=context.step_name,
            error_type="UnstructuredDiagnosis",
            root_cause=raw_response or context.error_message,
            summary=f"Analysis completed for step '{context.step_name}'",
            suggested_fix="Review failure details and logs.",
            confidence_score=0.7,
            raw_llm_response=raw_response,
            provider=provider_name,
        )

    def format_report_for_ui(self, report: DiagnosisReport) -> Dict[str, Any]:
        """
        Outputs root-cause diagnosis report formatted for pipeline UI presentation.
        """
        return {
            "title": f"🚨 Failure Diagnosis: {report.step_name}",
            "step_id": report.step_id,
            "provider": report.provider.upper(),
            "confidence": f"{int(report.confidence_score * 100)}%",
            "error_type": report.error_type,
            "summary": report.summary,
            "root_cause": report.root_cause,
            "suggested_fix": report.suggested_fix,
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime(report.timestamp)),
            "raw": report.model_dump() if hasattr(report, "model_dump") else report.dict(),
        }
