"""
Self-Healing Sandbox & Patch Generation Engine for OpenHarness / LocalAgentSandbox.
Utilizes AI root-cause diagnosis reports to generate code patches via subagents,
provisions isolated sandbox environments to apply patches and re-run failing tests,
and presents verified diffs to developers for manual review.
"""

import difflib
import json
import os
import re
import time
import uuid
from typing import Dict, List, Optional, Any, Union, Callable
from pydantic import BaseModel, Field

from .diagnostics import DiagnosisReport, BaseProviderAdapter, get_provider_adapter
from .orchestrator import UniverseOrchestrator, Universe, ComputeQuota, UniverseStatus


class GeneratedPatch(BaseModel):
    """Represents a code patch generated by the Self-Healing subagent."""
    patch_id: str
    step_id: str
    target_file: str
    explanation: str
    original_code: str
    patched_code: str
    diff: str
    confidence_score: float = 0.85
    timestamp: float = Field(default_factory=time.time)


class PatchVerificationResult(BaseModel):
    """Result of running patch verification inside an isolated sandbox environment."""
    patch_id: str
    sandbox_id: str
    verified: bool
    test_passed: bool
    test_output: str
    execution_time_seconds: float
    timestamp: float = Field(default_factory=time.time)


class SelfHealingReport(BaseModel):
    """Complete remediation report presented to developers for manual review."""
    report_id: str
    diagnosis: DiagnosisReport
    patch: GeneratedPatch
    verification: PatchVerificationResult
    review_status: str = "PENDING_DEVELOPER_REVIEW"
    timestamp: float = Field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        """Converts report to dictionary representation."""
        if hasattr(self, "model_dump"):
            return self.model_dump()
        return self.dict()

    def format_review_text(self) -> str:
        """Formats the verified patch diff and test report for human developer review."""
        lines = []
        lines.append("=" * 80)
        lines.append("🛠️ OpenHarness Self-Healing Sandbox & Verified Patch Report")
        lines.append("=" * 80)
        lines.append(f"Report ID:      {self.report_id}")
        lines.append(f"Step ID:        {self.diagnosis.step_id} ({self.diagnosis.step_name})")
        lines.append(f"Error Type:     {self.diagnosis.error_type}")
        lines.append(f"Root Cause:     {self.diagnosis.root_cause}")
        lines.append(f"Suggested Fix:  {self.diagnosis.suggested_fix}")
        lines.append(f"Patch ID:       {self.patch.patch_id}")
        lines.append(f"Target File:    {self.patch.target_file}")
        lines.append(f"Sandbox ID:     {self.verification.sandbox_id}")

        status_symbol = "✅ VERIFIED PASS" if self.verification.verified else "❌ VERIFICATION FAILED"
        lines.append(f"Verification:   {status_symbol} ({self.verification.execution_time_seconds:.3f}s)")
        lines.append(f"Review Status:  {self.review_status}")
        lines.append("")
        lines.append("-" * 80)
        lines.append("💡 Proposed Fix Explanation")
        lines.append("-" * 80)
        lines.append(self.patch.explanation)
        lines.append("")
        lines.append("-" * 80)
        lines.append("📝 Unified Code Patch Diff (For Manual Developer Review)")
        lines.append("-" * 80)
        if self.patch.diff.strip():
            lines.append(self.patch.diff.strip())
        else:
            lines.append("No diff changes generated.")
        lines.append("")
        lines.append("-" * 80)
        lines.append("🧪 Sandbox Test Verification Output")
        lines.append("-" * 80)
        lines.append(self.verification.test_output.strip() or "No test output recorded.")
        lines.append("=" * 80)
        return "\n".join(lines)


class PatchGeneratorAgent:
    """
    Subagent that utilizes root-cause diagnosis reports and source context
    to generate candidate code patches using LLM adapters or heuristic fallback.
    """

    def __init__(
        self,
        provider: Union[str, BaseProviderAdapter] = "google",
        api_key: Optional[str] = None,
        model: Optional[str] = None,
    ):
        if isinstance(provider, BaseProviderAdapter):
            self.provider = provider
        else:
            self.provider = get_provider_adapter(provider_name=provider, api_key=api_key, model=model)

    def generate_patch(
        self,
        diagnosis: DiagnosisReport,
        target_file: str,
        original_code: str,
    ) -> GeneratedPatch:
        """
        Generates a code patch to fix the error identified in the DiagnosisReport.

        Args:
            diagnosis: The root-cause DiagnosisReport from the AI Diagnostics Engine.
            target_file: Path or filename of the target file needing repair.
            original_code: Current source code string of the target file.

        Returns:
            GeneratedPatch object containing the unified diff and proposed patched code.
        """
        system_prompt = (
            "You are an expert AI Autonomous Code Repair Subagent. "
            "Analyze the root-cause diagnosis report and source code, and generate a fixed version of the code. "
            "Return ONLY valid JSON matching this schema:\n"
            "{\n"
            '  "explanation": "Detailed rationale for the code changes",\n'
            '  "patched_code": "Complete modified source code string"\n'
            "}"
        )

        user_prompt = (
            f"Failed Step ID: {diagnosis.step_id}\n"
            f"Error Type: {diagnosis.error_type}\n"
            f"Root Cause: {diagnosis.root_cause}\n"
            f"Suggested Fix: {diagnosis.suggested_fix}\n"
            f"Target File: {target_file}\n\n"
            f"Original Source Code:\n
