"""
Models and data structures for Self-Healing Sandbox & Patch Generation Engine.
"""

import time
from typing import Dict, Any
from pydantic import BaseModel, Field

from .diagnostics import DiagnosisReport


class GeneratedPatch(BaseModel):
    """Represents a code patch generated by the Self-Healing subagent."""
    patch_id: str
    step_id: str
    target_file: str
    explanation: str
    original_code: str
    patched_code: str
    diff: str
    confidence_score: float = 0.85
    timestamp: float = Field(default_factory=time.time)


class PatchVerificationResult(BaseModel):
    """Result of running patch verification inside an isolated sandbox environment."""
    patch_id: str
    sandbox_id: str
    verified: bool
    test_passed: bool
    test_output: str
    execution_time_seconds: float
    timestamp: float = Field(default_factory=time.time)


class SelfHealingReport(BaseModel):
    """Complete remediation report presented to developers for manual review."""
    report_id: str
    diagnosis: DiagnosisReport
    patch: GeneratedPatch
    verification: PatchVerificationResult
    review_status: str = "PENDING_DEVELOPER_REVIEW"
    timestamp: float = Field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        """Converts report to dictionary representation."""
        if hasattr(self, "model_dump"):
            return self.model_dump()
        return self.dict()

    def format_review_text(self) -> str:
        """Formats the verified patch diff and test report for human developer review."""
        lines = []
        lines.append("=" * 80)
        lines.append("🛠️ OpenHarness Self-Healing Sandbox & Verified Patch Report")
        lines.append("=" * 80)
        lines.append(f"Report ID:      {self.report_id}")
        lines.append(f"Step ID:        {self.diagnosis.step_id} ({self.diagnosis.step_name})")
        lines.append(f"Error Type:     {self.diagnosis.error_type}")
        lines.append(f"Root Cause:     {self.diagnosis.root_cause}")
        lines.append(f"Suggested Fix:  {self.diagnosis.suggested_fix}")
        lines.append(f"Patch ID:       {self.patch.patch_id}")
        lines.append(f"Target File:    {self.patch.target_file}")
        lines.append(f"Sandbox ID:     {self.verification.sandbox_id}")

        status_symbol = "✅ VERIFIED PASS" if self.verification.verified else "❌ VERIFICATION FAILED"
        lines.append(f"Verification:   {status_symbol} ({self.verification.execution_time_seconds:.3f}s)")
        lines.append(f"Review Status:  {self.review_status}")
        lines.append("")
        lines.append("-" * 80)
        lines.append("💡 Proposed Fix Explanation")
        lines.append("-" * 80)
        lines.append(self.patch.explanation)
        lines.append("")
        lines.append("-" * 80)
        lines.append("📝 Unified Code Patch Diff (For Manual Developer Review)")
        lines.append("-" * 80)
        if self.patch.diff.strip():
            lines.append(self.patch.diff.strip())
        else:
            lines.append("No diff changes generated.")
        lines.append("")
        lines.append("-" * 80)
        lines.append("🧪 Sandbox Test Verification Output")
        lines.append("-" * 80)
        lines.append(self.verification.test_output.strip() or "No test output recorded.")
        lines.append("=" * 80)
        return "\n".join(lines)
