"""
Fleet configuration management for OpenHarness HarnessFleet.
Handles generation and loading of fleet.yaml configuration files.
"""
from __future__ import annotations

import os
from typing import Any, Dict, List, Optional
from openharness.fleet.models import (
    FleetConfig,
    WorkerCapabilities,
    WorkerSpec,
)

_TEMPLATE = """# OpenHarness Fleet Configuration
# Generated by `harness fleet init`
version: "{version}"

conductor:
  host: {conductor_host}
  port: {conductor_port}
  heartbeat_interval_sec: {heartbeat_interval}
  heartbeat_miss_threshold: {heartbeat_miss_threshold}

# Static worker list (also supports mDNS/K8s discovery at runtime)
workers:
{workers_yaml}

scheduling:
  shard_mode: {shard_mode}
  max_skew_pct: {max_skew_pct}
  default_timeout_sec: {default_timeout}
"""

_WORKER_TEMPLATE = """  - id: "{worker_id}"
    host: {host}
    port: {port}
    capabilities:
      os: {os}
      arch: {arch}
      gpu: {gpu}
"""


def generate_fleet_yaml(
    path: str = "fleet.yaml",
    conductor_host: str = "0.0.0.0",
    conductor_port: int = 8900,
    heartbeat_interval: int = 5,
    heartbeat_miss_threshold: int = 3,
    workers: Optional[List[Dict[str, Any]]] = None,
    shard_mode: str = "auto",
    max_skew_pct: int = 20,
    default_timeout: int = 300,
) -> str:
    """Generate a fleet.yaml configuration file.

    Args:
        path: Output file path.
        conductor_host: Conductor bind address.
        conductor_port: Conductor bind port.
        heartbeat_interval: Seconds between expected worker heartbeats.
        heartbeat_miss_threshold: Consecutive misses before marking UNHEALTHY.
        workers: List of worker spec dicts (id, host, port, capabilities).
        shard_mode: Sharding strategy ('auto' or 'manual').
        max_skew_pct: Maximum allowed shard wall-clock skew percentage.
        default_timeout: Default test timeout in seconds.

    Returns:
        Absolute path to the written file.
    """
    if workers is None:
        workers = [
            {
                "id": "local-1",
                "host": "127.0.0.1",
                "port": 9001,
                "os": "linux",
                "arch": "x86_64",
                "gpu": False,
            },
        ]

    workers_yaml = ""
    for w in workers:
        workers_yaml += _WORKER_TEMPLATE.format(
            worker_id=w.get("id", "worker-1"),
            host=w.get("host", "127.0.0.1"),
            port=w.get("port", 9000),
            os=w.get("capabilities", {}).get("os", "linux"),
            arch=w.get("capabilities", {}).get("arch", "x86_64"),
            gpu=str(w.get("capabilities", {}).get("gpu", False)).lower(),
        )

    content = _TEMPLATE.format(
        version="1.0",
        conductor_host=conductor_host,
        conductor_port=conductor_port,
        heartbeat_interval=heartbeat_interval,
        heartbeat_miss_threshold=heartbeat_miss_threshold,
        workers_yaml=workers_yaml,
        shard_mode=shard_mode,
        max_skew_pct=max_skew_pct,
        default_timeout=default_timeout,
    )

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return os.path.abspath(path)


def load_fleet_yaml(path: str = "fleet.yaml") -> FleetConfig:
    """Load and parse a fleet.yaml configuration file.

    Uses a simple YAML subset parser (no external dependency required).
    Supports the structure generated by ``generate_fleet_yaml``.
    """
    with open(path, "r", encoding="utf-8") as f:
        raw = f.read()
    data = _parse_yaml(raw)
    if data is None:
        data = {}
    return _dict_to_config(data)


def _parse_yaml(text: str) -> Dict[str, Any]:
    """Parse a simple subset of YAML (matching fleet.yaml structure).

    Supports: nested dicts, lists of dicts, string/int/bool/scalar values.
    """
    result: Dict[str, Any] = {}
    stack: List[tuple[int, Any]] = [(-1, result)]
    lines = text.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.lstrip()
        if not stripped or stripped.startswith("#"):
            i += 1
            continue
        indent = len(line) - len(stripped)

        while stack and stack[-1][0] > indent and len(stack) > 1:
            stack.pop()

        current_parent = stack[-1][1]

        if stripped.startswith("- "):
            item_text = stripped[2:].strip()
            if not isinstance(current_parent, list):
                i += 1
                continue
            if ":" in item_text:
                key, _, val = item_text.partition(":")
                key = key.strip().strip('"').strip("'")
                val = val.strip()
                new_dict: Dict[str, Any] = {key: _coerce_value(val)}
                current_parent.append(new_dict)
                stack.append((indent + 2, new_dict))
            else:
                current_parent.append(_coerce_value(item_text))
        elif ":" in stripped:
            key, _, val = stripped.partition(":")
            key = key.strip().strip('"').strip("'")
            val = val.strip()
            if val:
                if isinstance(current_parent, dict):
                    current_parent[key] = _coerce_value(val)
            else:
                if isinstance(current_parent, dict):
                    if _is_list_header(lines, i):
                        new_list: List[Any] = []
                        current_parent[key] = new_list
                        stack.append((indent + 2, new_list))
                    else:
                        new_dict2: Dict[str, Any] = {}
                        current_parent[key] = new_dict2
                        stack.append((indent + 2, new_dict2))
        i += 1
    return result


def _is_list_header(lines: List[str], idx: int) -> bool:
    """Check if the next non-empty, non-comment line starts with '-'."""
    j = idx + 1
    while j < len(lines):
        s = lines[j].lstrip()
        if s and not s.startswith("#"):
            return s.startswith("- ")
        j += 1
    return False


def _coerce_value(val: str) -> Any:
    """Convert a YAML string value to the appropriate Python type."""
    val = val.strip().strip('"').strip("'")
    if val.lower() == "true":
        return True
    if val.lower() == "false":
        return False
    if val.lower() in ("null", "~"):
        return None
    try:
        return int(val)
    except ValueError:
        pass
    try:
        return float(val)
    except ValueError:
        pass
    return val


def _dict_to_config(data: Dict[str, Any]) -> FleetConfig:
    """Convert a parsed YAML dict to a FleetConfig model."""
    workers_raw = data.get("workers", [])
    worker_specs: List[WorkerSpec] = []
    if isinstance(workers_raw, dict):
        workers_raw = []
    for w in workers_raw:
        if not isinstance(w, dict):
            continue
        caps = w.get("capabilities", {})
        if not isinstance(caps, dict):
            caps = {}
        spec = WorkerSpec(
            id=w.get("id"),
            host=w.get("host", "127.0.0.1"),
            port=w.get("port", 9000),
            capabilities=WorkerCapabilities(
                os=caps.get("os", "linux"),
                arch=caps.get("arch", "x86_64"),
                gpu=caps.get("gpu", False),
                browsers=caps.get("browsers", []),
            ),
            ephemeral=w.get("ephemeral", False),
        )
        worker_specs.append(spec)

    return FleetConfig(
        version=str(data.get("version", "1.0")),
        conductor=data.get("conductor", {}),
        workers=worker_specs,
        scheduling=data.get("scheduling", {}),
    )
